# Numpy For Dataset

In [13]:
## Rows   → samples (data points)
## Columns → features (attributes)

In [4]:
import numpy as np

In [6]:
data = np.array([                               
    [22,50000,1],
    [25,60000,0],
    [30,80000,1]
])
# 3 samples and 3 features


In [7]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
# Random Dataset
data = np.random.rand(10, 5)
data
# 10 samples, 5 features

array([[0.61022212, 0.10246317, 0.4410533 , 0.63063114, 0.79420306],
       [0.25801598, 0.15082848, 0.4303872 , 0.30030028, 0.02259223],
       [0.57054483, 0.5366928 , 0.40560547, 0.95518977, 0.14271494],
       [0.94612537, 0.3889081 , 0.88447636, 0.89773149, 0.75738753],
       [0.2025085 , 0.7338939 , 0.87248613, 0.95529739, 0.46513552],
       [0.04672788, 0.28391349, 0.6977477 , 0.00961462, 0.40322315],
       [0.91037175, 0.5959624 , 0.44687636, 0.33501526, 0.8321523 ],
       [0.44697735, 0.52071262, 0.39672173, 0.30728624, 0.00315419],
       [0.56591854, 0.4078314 , 0.62412582, 0.5867819 , 0.96229598],
       [0.55398718, 0.97694261, 0.72369837, 0.51046019, 0.91394159]])

In [12]:
# Integer Dataset
data = np.random.randint(0, 100, (5,3))    # numpy.random.randint(low, high, size)
data

array([[81, 72, 93],
       [68, 43, 26],
       [23, 75, 76],
       [75, 23, 24],
       [73, 12,  9]], dtype=int32)

In [20]:
# Dataset Shape and Size
print(data.shape)             # (rows, columns)
print(data.ndim)              # number of dimensions
print(data.size)              # total elements
print(data.dtype)             # data type

(5, 3)
2
15
int32


In [21]:
# Row and Column Access
data[0]    # Access Row

array([81, 72, 93], dtype=int32)

In [23]:
data[:,0]   # Access Column

array([81, 68, 23, 75, 73], dtype=int32)

In [24]:
# Specific Value
data[2,1]

np.int32(75)

In [32]:
# Slicing
print(data[1,2])       # Selcet Rows
print(data[:, 0:2])    # Select Columns
print(data[0:1, 0:2])     # Select Rows and Columns

26
[[81 72]
 [68 43]
 [23 75]
 [75 23]
 [73 12]]
[[81 72]]


In [34]:
# Dataset Splitting
x = data[:, :-1]     # features
x

array([[81, 72],
       [68, 43],
       [23, 75],
       [75, 23],
       [73, 12]], dtype=int32)

In [35]:
y = data[:, -1]     # label
y

array([93, 26, 76, 24,  9], dtype=int32)

In [39]:
# Train/Test split (manual):

import numpy as np

# 1. Define the dataset (X)
X = np.array([[81, 72, 93],
              [68, 43, 26],
              [23, 75, 76],
              [75, 23, 24],
              [73, 12,  9]])

# 2. Create a dummy y (Labels) - must be the same length as X
y = np.array([1, 0, 1, 0, 1]) 

# 3. Calculate split (5 * 0.8 = 4)
split = int(0.8 * len(X))

# 4. Perform the slice (Ensuring X is capitalized consistently)
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

print(f"X_train rows: {len(X_train)}") # Output: 4
print(f"X_test rows: {len(X_test)}")   # Output: 1


X_train rows: 4
X_test rows: 1


In [40]:
data = np.array([1,2, np.nan, 4])
data

array([ 1.,  2., nan,  4.])

In [43]:
print(np.isnan(data))

[False False  True False]


In [49]:
data[np.isnan(data)] = np.nanmean(data)
data

array([1.        , 2.        , 2.33333333, 4.        ])

In [50]:
data.mean()

np.float64(2.3333333333333335)

In [51]:
data.std()

np.float64(1.0801234497346432)

In [52]:
data.min()

np.float64(1.0)

In [53]:
data.max()

np.float64(4.0)

In [55]:
norm = (data - data.min(axis=0)) / (data.max(axis=0) - data.min(axis=0))
norm

array([0.        , 0.33333333, 0.44444444, 1.        ])

In [56]:
standard = (data - data.mean(axis=0)) / data.std(axis=0)
standard

array([-1.2344268, -0.3086067,  0.       ,  1.5430335])